<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitef814452644258bbd17c1126e775f518
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/Twilio',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitef814452644258bbd17c1126e775f518::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitef814452644258bbd17c1126e775f518::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
